# Generated by Django 3.1.3 on 2021-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hood',
            field=models.CharField(default='36A', max_length=8),
            preserve_default=False,
        ),
    ]
